In [1]:
import numpy as np

In [11]:
l1=[1,2,3]
l2=[7,8,9]
ar=np.array([l1,l2])
ar

array([[1, 2, 3],
       [7, 8, 9]])

In [25]:
ar.shape

(2, 3)

In [26]:
ar.reshape(3,2)

array([[1, 2],
       [3, 7],
       [8, 9]])

In [62]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [38]:
li1=[9,8,7]
li2=[6,5,4]
li3=[3,2,1]
arr=np.array([li1,li2,li3])
arr


array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [39]:
arr[0:2,:]  ##Accessing till the second row

array([[9, 8, 7],
       [6, 5, 4]])

In [40]:
arr[:,0:2] ##Accessing till the second column

array([[9, 8],
       [6, 5],
       [3, 2]])

In [42]:
a=np.arange(0,10) ##Makes an array of range 0 to 10
a 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a=np.arange(0,10,step=2) 
a

array([0, 2, 4, 6, 8])

In [45]:
a=np.linspace(0,10,50) ##For 50 equally divided space for 0 to 10
a

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [46]:
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [47]:
b[3:]=50
b

array([ 1,  2,  3, 50, 50])

In [49]:
c=b.copy()
print(c)

[ 1  2  3 50 50]


In [52]:
c[3:]=100
c

array([  1,   2,   3, 100, 100])

In [56]:
c[c<10] ##elements in array less than 10

array([1, 2, 3])

In [57]:
array=[9,8,7]
array*2

[9, 8, 7, 9, 8, 7]